-- Generated by scripts/gen-seed.ts — do not edit by hand.

insert into public.courses (id,num,sym,title,subject,area,tags,instructor,role,price,mrp,rating,reviews,students,lessons,hours,level,grade,cover,ink,pop,description,learn) values
  ('imo','01','Nt','Olympiad Mathematics: Number Theory','Number Theory','Mathematics',array['Olympiad','Mathematics']::text[],'Dr. Ananya Rao','IMO Silver · IISc Bangalore',2499,4999,4.9,'2.1k','12.4k',48,22,'Advanced','Grade 8–12','#0A1F4D','#3DD6CF',98,'Olympiad Mathematics: Number Theory is a carefully sequenced course by Dr. Ananya Rao. Every lesson pairs a short, beautifully produced video with worked examples and graded practice — built for students who want depth, not shortcuts.',array['Build intuition for divisibility, primes and modular arithmetic','Solve olympiad problems with invariants and extremal arguments','Write clean, rigorous proofs examiners love','Pace yourself through 3-hour papers']::text[]),
  ('phy','02','Ph','Physics Olympiad: Mechanics from First Principles','Mechanics','Science',array['Olympiad','Science']::text[],'Prof. Vikram Sethi','Former IPhO coach · IIT Delhi',2999,5499,4.8,'1.6k','9.1k',42,19,'Advanced','Grade 9–12','#0B4FB3','#D4E5FF',91,'Physics Olympiad: Mechanics from First Principles is a carefully sequenced course by Prof. Vikram Sethi. Every lesson pairs a short, beautifully produced video with worked examples and graded practice — built for students who want depth, not shortcuts.',array['Master the core concepts with visual, first-principles explanations','Tackle multi-step numericals with confidence','Learn the experimental reasoning olympiads test','Practise with 400+ graded problems']::text[]),
  ('chem','03','Ch','Organic Chemistry, Illuminated','Chemistry','Science',array['Science','Competitive']::text[],'Dr. Meera Iyer','Author · 18 yrs teaching',1999,3499,4.7,'1.2k','7.8k',36,16,'Intermediate','Grade 11–12','#0F9D8F','#EEF0FB',80,'Organic Chemistry, Illuminated is a carefully sequenced course by Dr. Meera Iyer. Every lesson pairs a short, beautifully produced video with worked examples and graded practice — built for students who want depth, not shortcuts.',array['Master the core concepts with visual, first-principles explanations','Tackle multi-step numericals with confidence','Learn the experimental reasoning olympiads test','Practise with 400+ graded problems']::text[]),
  ('bio','04','Bi','Biology Olympiad Foundations','Biology','Science',array['Olympiad','Science']::text[],'Dr. Kavya Nair','IBO mentor · AIIMS',1799,2999,4.8,'940','6.3k',30,14,'Beginner','Grade 6–10','#17A673','#EEF0FB',76,'Biology Olympiad Foundations is a carefully sequenced course by Dr. Kavya Nair. Every lesson pairs a short, beautifully produced video with worked examples and graded practice — built for students who want depth, not shortcuts.',array['Master the core concepts with visual, first-principles explanations','Tackle multi-step numericals with confidence','Learn the experimental reasoning olympiads test','Practise with 400+ graded problems']::text[]),
  ('cs','05','Cs','Informatics Olympiad: Algorithms in C++','Algorithms','Coding',array['Olympiad','Coding']::text[],'Arjun Menon','IOI Bronze · Google',3499,6999,4.9,'1.8k','6.2k',54,28,'Advanced','Grade 8–12','#6B4EFF','#3DD6CF',94,'Informatics Olympiad: Algorithms in C++ is a carefully sequenced course by Arjun Menon. Every lesson pairs a short, beautifully produced video with worked examples and graded practice — built for students who want depth, not shortcuts.',array['Think in algorithms: greedy, DP, graphs','Write fast, bug-free C++ under time pressure','Analyse complexity like a judge','Simulate real contest rounds']::text[]),
  ('eng','06','En','English Olympiad: Grammar & Usage','English','Languages',array['Olympiad','Languages']::text[],'Sarah D''Souza','Cambridge CELTA · 12 yrs',999,1999,4.6,'3.4k','15k',28,11,'Beginner','Grade 6–10','#0172EA','#EEF5FF',88,'English Olympiad: Grammar & Usage is a carefully sequenced course by Sarah D''Souza. Every lesson pairs a short, beautifully produced video with worked examples and graded practice — built for students who want depth, not shortcuts.',array['Command grammar, usage and vocabulary','Read closely and answer precisely','Write with clarity and style','Ace comprehension under the clock']::text[]),
  ('jee','07','Al','JEE Foundation: Algebra','Algebra','Mathematics',array['Competitive','Mathematics']::text[],'Rohit Bansal','JEE AIR 42 · IIT Bombay',3999,7999,4.8,'4.2k','21k',60,32,'Intermediate','Grade 9–11','#E5484D','#D4E5FF',96,'JEE Foundation: Algebra is a carefully sequenced course by Rohit Bansal. Every lesson pairs a short, beautifully produced video with worked examples and graded practice — built for students who want depth, not shortcuts.',array['Build intuition for divisibility, primes and modular arithmetic','Solve olympiad problems with invariants and extremal arguments','Write clean, rigorous proofs examiners love','Pace yourself through 3-hour papers']::text[]),
  ('astro','08','As','Astronomy Olympiad: The Night Sky','Astronomy','Science',array['Olympiad','Science']::text[],'Dr. Neel Kapoor','Astrophysicist · IUCAA',1499,2499,4.7,'610','3.9k',24,10,'Intermediate','Grade 8–12','#123A80','#EEF0FB',70,'Astronomy Olympiad: The Night Sky is a carefully sequenced course by Dr. Neel Kapoor. Every lesson pairs a short, beautifully produced video with worked examples and graded practice — built for students who want depth, not shortcuts.',array['Master the core concepts with visual, first-principles explanations','Tackle multi-step numericals with confidence','Learn the experimental reasoning olympiads test','Practise with 400+ graded problems']::text[]),
  ('eco','09','Ec','Economics for Curious Minds','Economics','Humanities',array['Humanities']::text[],'Priya Raman','LSE · Policy researcher',1299,1999,4.6,'480','2.7k',20,8,'Beginner','Grade 9–12','#3DD6CF','#0A1F4D',62,'Economics for Curious Minds is a carefully sequenced course by Priya Raman. Every lesson pairs a short, beautifully produced video with worked examples and graded practice — built for students who want depth, not shortcuts.',array['Think like an economist about everyday choices','Read graphs, data and policy','Debate trade-offs with evidence','Prepare for commerce olympiads']::text[]),
  ('geo','10','Gm','Geometry for Olympiads','Geometry','Mathematics',array['Olympiad','Mathematics']::text[],'Dr. Ananya Rao','IMO Silver · IISc Bangalore',2299,3999,4.9,'1.1k','8.6k',40,18,'Intermediate','Grade 7–12','#EEF0FB','#0B4FB3',85,'Geometry for Olympiads is a carefully sequenced course by Dr. Ananya Rao. Every lesson pairs a short, beautifully produced video with worked examples and graded practice — built for students who want depth, not shortcuts.',array['Build intuition for divisibility, primes and modular arithmetic','Solve olympiad problems with invariants and extremal arguments','Write clean, rigorous proofs examiners love','Pace yourself through 3-hour papers']::text[])
on conflict (id) do nothing;

insert into public.lessons (id,course_id,position,title,duration) values
  ('imo-1','imo',0,'Why number theory?','08:20'),
  ('imo-2','imo',1,'Divisibility & primes','18:45'),
  ('imo-3','imo',2,'GCD and Euclid’s algorithm','21:10'),
  ('imo-4','imo',3,'Modular arithmetic','24:00'),
  ('imo-5','imo',4,'Fermat’s little theorem','19:30'),
  ('imo-6','imo',5,'Chinese remainder theorem','26:15'),
  ('imo-7','imo',6,'Diophantine equations','22:40'),
  ('imo-8','imo',7,'Problem set: Week 2','35:00'),
  ('phy-1','phy',0,'Welcome & course map','08:20'),
  ('phy-2','phy',1,'Foundations','18:45'),
  ('phy-3','phy',2,'Core techniques','21:10'),
  ('phy-4','phy',3,'Worked examples','24:00'),
  ('phy-5','phy',4,'Problem-solving patterns','19:30'),
  ('phy-6','phy',5,'Olympiad-level practice','26:15'),
  ('phy-7','phy',6,'Full mock & review','22:40'),
  ('phy-8','phy',7,'Problem set: Week 2','35:00'),
  ('chem-1','chem',0,'Welcome & course map','08:20'),
  ('chem-2','chem',1,'Foundations','18:45'),
  ('chem-3','chem',2,'Core techniques','21:10'),
  ('chem-4','chem',3,'Worked examples','24:00'),
  ('chem-5','chem',4,'Problem-solving patterns','19:30'),
  ('chem-6','chem',5,'Olympiad-level practice','26:15'),
  ('chem-7','chem',6,'Full mock & review','22:40'),
  ('chem-8','chem',7,'Problem set: Week 2','35:00'),
  ('bio-1','bio',0,'Welcome & course map','08:20'),
  ('bio-2','bio',1,'Foundations','18:45'),
  ('bio-3','bio',2,'Core techniques','21:10'),
  ('bio-4','bio',3,'Worked examples','24:00'),
  ('bio-5','bio',4,'Problem-solving patterns','19:30'),
  ('bio-6','bio',5,'Olympiad-level practice','26:15'),
  ('bio-7','bio',6,'Full mock & review','22:40'),
  ('bio-8','bio',7,'Problem set: Week 2','35:00'),
  ('cs-1','cs',0,'Welcome & course map','08:20'),
  ('cs-2','cs',1,'Foundations','18:45'),
  ('cs-3','cs',2,'Core techniques','21:10'),
  ('cs-4','cs',3,'Worked examples','24:00'),
  ('cs-5','cs',4,'Problem-solving patterns','19:30'),
  ('cs-6','cs',5,'Olympiad-level practice','26:15'),
  ('cs-7','cs',6,'Full mock & review','22:40'),
  ('cs-8','cs',7,'Problem set: Week 2','35:00'),
  ('eng-1','eng',0,'Welcome & course map','08:20'),
  ('eng-2','eng',1,'Foundations','18:45'),
  ('eng-3','eng',2,'Core techniques','21:10'),
  ('eng-4','eng',3,'Worked examples','24:00'),
  ('eng-5','eng',4,'Problem-solving patterns','19:30'),
  ('eng-6','eng',5,'Olympiad-level practice','26:15'),
  ('eng-7','eng',6,'Full mock & review','22:40'),
  ('eng-8','eng',7,'Problem set: Week 2','35:00'),
  ('jee-1','jee',0,'Welcome & course map','08:20'),
  ('jee-2','jee',1,'Foundations','18:45'),
  ('jee-3','jee',2,'Core techniques','21:10'),
  ('jee-4','jee',3,'Worked examples','24:00'),
  ('jee-5','jee',4,'Problem-solving patterns','19:30'),
  ('jee-6','jee',5,'Olympiad-level practice','26:15'),
  ('jee-7','jee',6,'Full mock & review','22:40'),
  ('jee-8','jee',7,'Problem set: Week 2','35:00'),
  ('astro-1','astro',0,'Welcome & course map','08:20'),
  ('astro-2','astro',1,'Foundations','18:45'),
  ('astro-3','astro',2,'Core techniques','21:10'),
  ('astro-4','astro',3,'Worked examples','24:00'),
  ('astro-5','astro',4,'Problem-solving patterns','19:30'),
  ('astro-6','astro',5,'Olympiad-level practice','26:15'),
  ('astro-7','astro',6,'Full mock & review','22:40'),
  ('astro-8','astro',7,'Problem set: Week 2','35:00'),
  ('eco-1','eco',0,'Welcome & course map','08:20'),
  ('eco-2','eco',1,'Foundations','18:45'),
  ('eco-3','eco',2,'Core techniques','21:10'),
  ('eco-4','eco',3,'Worked examples','24:00'),
  ('eco-5','eco',4,'Problem-solving patterns','19:30'),
  ('eco-6','eco',5,'Olympiad-level practice','26:15'),
  ('eco-7','eco',6,'Full mock & review','22:40'),
  ('eco-8','eco',7,'Problem set: Week 2','35:00'),
  ('geo-1','geo',0,'Welcome & course map','08:20'),
  ('geo-2','geo',1,'Foundations','18:45'),
  ('geo-3','geo',2,'Core techniques','21:10'),
  ('geo-4','geo',3,'Worked examples','24:00'),
  ('geo-5','geo',4,'Problem-solving patterns','19:30'),
  ('geo-6','geo',5,'Olympiad-level practice','26:15'),
  ('geo-7','geo',6,'Full mock & review','22:40'),
  ('geo-8','geo',7,'Problem set: Week 2','35:00')
on conflict (id) do nothing;

insert into public.exams (id,name,exam_date,meta,reg_closes_at) values
  ('emo','Elden Mathematics Olympiad','2026-11-16','Grades 6–12 · Online · ₹149','2026-10-16T23:59:00+05:30'),
  ('nso','National Science Olympiad — Level 1','2026-12-04','Grades 6–12 · School centre · ₹125',null),
  ('ieo','International English Olympiad','2026-12-12','Grades 6–12 · Online · ₹125',null),
  ('eic','Elden Informatics Challenge','2027-01-10','Grades 8–12 · Online · Free',null),
  ('nao','National Astronomy Olympiad','2027-01-25','Grades 9–12 · Centre · ₹200',null)
on conflict (id) do nothing;

-- Live class times are relative to when the seed runs.
insert into public.live_classes (id,title,host,starts_at,is_live,watching) values
  ('g1','Geometry Masterclass: Circles & Power of a Point','Dr. Ananya Rao',now() - interval '42 minutes',true,1284),
  ('p1','Physics Doubt Clinic: Rotational Motion','Prof. Vikram Sethi',date_trunc('day', now()) + interval '20 hours',false,0),
  ('p2','Parents’ Webinar: Choosing the Right Olympiad','ElMaster Admissions',date_trunc('day', now()) + interval '1 day 17 hours 30 minutes',false,0),
  ('p3','EMO Strategy Session — The Last 30 Days','Team ElMaster',date_trunc('day', now()) + interval '6 days 11 hours',false,0)
on conflict (id) do nothing;

insert into public.quiz_questions (mock_id,position,question,options,answer) values
  ('nt-sprint',0,'What is the remainder when 2¹⁰⁰ is divided by 7?',array['1','2','4','6']::text[],1),
  ('nt-sprint',1,'How many positive divisors does 360 have?',array['18','20','24','30']::text[],2),
  ('nt-sprint',2,'A convex polygon has interior angles summing to 1440°. How many sides does it have?',array['8','9','10','12']::text[],2),
  ('nt-sprint',3,'If x + 1/x = 3, what is x² + 1/x²?',array['5','7','9','11']::text[],1),
  ('nt-sprint',4,'What is the last digit of 7²⁰²⁶?',array['1','3','7','9']::text[],3)
on conflict (mock_id, position) do nothing;

insert into public.coupons (code, percent) values ('ELDEN20', 20) on conflict (code) do nothing;
