// Writes supabase/seed.sql from lib/seed.ts so demo mode and the database
// start from the same catalog. Run: node scripts/gen-seed.ts
import { writeFileSync } from 'node:fs';
import { COURSES, LESSONS, EXAMS, QUIZ, FEATURED_EXAM, demoLiveClasses } from '../lib/seed.ts';

const s = (v: string) => `'${v.replace(/'/g, "''")}'`;
const arr = (a: string[]) => `array[${a.map(s).join(',')}]::text[]`;
const out: string[] = ['-- Generated by scripts/gen-seed.ts — do not edit by hand.', ''];

out.push('insert into public.courses (id,num,sym,title,subject,area,tags,instructor,role,price,mrp,rating,reviews,students,lessons,hours,level,grade,cover,ink,pop,description,learn) values');
out.push(COURSES.map(c => `  (${[s(c.id), s(c.num), s(c.sym), s(c.title), s(c.subject), s(c.area), arr(c.tags), s(c.instructor), s(c.role), c.price, c.mrp, c.rating, s(c.reviews), s(c.students), c.lessons, c.hours, s(c.level), s(c.grade), s(c.cover), s(c.ink), c.pop, s(c.desc), arr(c.learn)].join(',')})`).join(',\n') + '\non conflict (id) do nothing;\n');

out.push('insert into public.lessons (id,course_id,position,title,duration) values');
out.push(LESSONS.map(l => `  (${[s(l.id), s(l.courseId), l.position, s(l.title), s(l.duration)].join(',')})`).join(',\n') + '\non conflict (id) do nothing;\n');

out.push('insert into public.exams (id,name,exam_date,meta,reg_closes_at) values');
out.push(EXAMS.map(e => `  (${[s(e.id), s(e.name), s(e.date), s(e.meta), e.id === FEATURED_EXAM.id ? s(FEATURED_EXAM.regClosesAt) : 'null'].join(',')})`).join(',\n') + '\non conflict (id) do nothing;\n');

out.push("-- Live class times are relative to when the seed runs.");
out.push('insert into public.live_classes (id,title,host,starts_at,is_live,watching) values');
const offsets: Record<string, string> = { g1: "now() - interval '42 minutes'", p1: "date_trunc('day', now()) + interval '20 hours'", p2: "date_trunc('day', now()) + interval '1 day 17 hours 30 minutes'", p3: "date_trunc('day', now()) + interval '6 days 11 hours'" };
out.push(demoLiveClasses().map(l => `  (${[s(l.id), s(l.title), s(l.host), offsets[l.id], l.isLive, l.watching ?? 0].join(',')})`).join(',\n') + '\non conflict (id) do nothing;\n');

out.push('insert into public.quiz_questions (mock_id,position,question,options,answer) values');
out.push(QUIZ.map((q, i) => `  (${[s('nt-sprint'), i, s(q.q), arr(q.o), q.a].join(',')})`).join(',\n') + '\non conflict (mock_id, position) do nothing;\n');

out.push("insert into public.coupons (code, percent) values ('ELDEN20', 20) on conflict (code) do nothing;");
writeFileSync(new URL('../supabase/seed.sql', import.meta.url), out.join('\n') + '\n');
console.log('wrote supabase/seed.sql');
